### ISSUE TITLE
调用driver.quit()，macaca服务端报错

### ISSUE THREAD

**Issue by zhaozhiquan** [macacajs/macaca-chrome#13]
调用driver.quit()，macaca服务端报错，排查发现，是kill chrome进程时，没有兼容windows系统
![image](https://user-images.githubusercontent.com/25030068/117414287-8abc4600-af49-11eb-81ef-46b9843ebe42.png)
![image](https://user-images.githubusercontent.com/25030068/117414335-9871cb80-af49-11eb-93cc-401bf33b0c31.png)

**Comment by xudafeng** [comment]
@zhaozhiquan 可以尝试提个 pull request

**Comment by zhaozhiquan** [comment]
> @zhaozhiquan 可以尝试提个 pull request


> @zhaozhiquan可以尝试提个pull request
已提。哈哈哈。第一次提pr

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-chrome/commit/9f0ca6a523fbf95afb1c8efd9a39eb0e49d73c40

@zhaozhiquan
